# Generated by Django 3.1.6 on 2021-02-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name': 'Boss', 'verbose_name_plural': "Bosse's"},
        ),
    ]
