# Generated by Django 3.1.6 on 2021-02-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosses', '0007_auto_20210216_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='pwd',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='pwd'),
        ),
    ]
