# Generated by Django 3.1.6 on 2021-02-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
        ('bosses', '0009_auto_20210217_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='hit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hits.hit'),
        ),
    ]
