# Generated by Django 3.1.6 on 2021-02-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
        ('hitmans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitman',
            name='hit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hits.hit'),
        ),
    ]
