# Generated by Django 3.1.6 on 2021-02-17 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('hitmans', '0005_auto_20210216_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitman',
            name='profile',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='catalogs.profiles', verbose_name='Profile'),
        ),
    ]
