# Generated by Django 3.1.6 on 2021-02-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('hitmans', '0007_auto_20210217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitman',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogs.statushitman'),
        ),
    ]
