# Generated by Django 3.1.6 on 2021-02-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='Modified')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.statushits')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
