# Generated by Django 3.1.6 on 2021-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='registered',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Registered'),
        ),
    ]
